name: new_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # remote api
  http: ^0.13.3
  data_connection_checker: ^0.3.4
  # secure storage
  flutter_secure_storage: ^4.2.0
  path_provider: ^2.0.1

  # permission handler
  permission_handler: ^8.1.6
  google_maps_flutter: ^2.0.8

  dartz: ^0.9.2
  equatable: ^2.0.0
  # local mem
  shared_preferences: ^2.0.5
  # service locator
  get_it: ^7.1.3
  # business logic
  flutter_bloc: ^7.0.0
  provider: ^5.0.0
  # responsive design, font
  flutter_screenutil: ^5.0.0+2

  # svg icons
  flutter_svg: ^0.22.0

  # custom stepper
  timeline_tile: ^2.0.0

  carousel_slider: ^3.0.0

  # push notification
  flutter_local_notifications: ^5.0.0+4

  # firebase
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7

  # geo location

  geolocator: ^7.0.3
  geocoding: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo2.png
    - assets/icons/wine1.png
    - assets/icons/wine2.png
    - assets/icons/flag1.png
    - assets/icons/flag2.png
    - assets/icons/logo1.png
    - assets/icons/recycle_icon.svg
    - assets/icons/apple_pay.svg
    - assets/icons/apple_pay_2.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
